df <- AmnestyMeasure(cy = df, nexus_vars = "dtj", who_opts = "sta")
df <- AmnestyMeasure(cy = df, nexus_vars = c("dtj", "ctj"), who_opts = "sta")
df <- AmnestyMeasure(cy = df, nexus_vars = c("dtj", "ctj"), who_opts = "opp") 
df <- AmnestyMeasure(cy = df, nexus_vars = c("dtj", "ctj"), who_opts = c("sta", "opp")) 
df <- AmnestyMeasure(cy = df, nexus_vars = "ctj", who_opts = c("sta", "opp")) 
df <- AmnestyMeasure(cy = df, nexus_vars = "ctj", who_opts = "all") 
df <- AmnestyMeasure(cy = df, who_opts = "sta")
df <- AmnestyMeasure(cy = df, who_opts = "sta", what_opts = "hrv")
df <- AmnestyMeasure(cy = df, who_opts = "opp") 
df <- AmnestyMeasure(cy = df, who_opts = "opp", what_opts = "hrv")
df <- AmnestyMeasure(cy = df, who_opts = "pol")
df <- AmnestyMeasure(cy = df, peace_vars = "peaceSettlement") 
