library(here)
library(tidyverse)
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("lag", "dplyr")
conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("fixed", "stringr")

source(here("pipeline", "downloads.R"))
source(here("pipeline", "processing.R"))
source(here("pipeline", "cy.R"))
source(here("pipeline", "analysis_prep.R"))
# source(here("pipeline", "translation.R"))
# source(here("pipeline", "sql.R"))